vich_uploader:
    db_driver: orm

    mappings:
       images_projets:
           uri_prefix: '%app.path.images_projets%'
           upload_destination: '%kernel.project_dir%/public/%app.path.images_projets%'

       documentation_projets:
          uri_prefix: '%app.path.documentations_projets%'
          upload_destination: '%kernel.project_dir%/public/%app.path.documentations_projets%'
